# Noir-themed hunt configuration for November
hunt:
    min_hours_between_spawns: 2
    max_hours_between_spawns: 10
    allowed_channels:
      - "#your-channel"
    event_settings:
        escape_chance: 0.1
        min_flock_delay_minutes: 2
        max_flock_delay_minutes: 60
        min_flock_size: 20
        max_flock_size: 50
    animals:
        - name: "Rat"
          ascii_art: "<:3 )~~"
          hug_message: "{username} gently pets the Rat. It squeaks appreciatively."
          hunt_message: "{username} corners the Rat in a dead-end alley. Case closed."
        - name: "Stray Cat"
          ascii_art: "=^..^="
          hug_message: "{username} shares a moment with the Stray Cat. It understands the streets."
          hunt_message: "{username} gains the trust of the Stray Cat with a piece of dried fish. A useful ally."
        - name: "Watchdog"
          ascii_art: "[o_o]"
          hug_message: "{username} gives the Watchdog a pat. It's been trained not to bite."
          hunt_message: "{username} outsmarts the Watchdog. Every security system has a weakness."
        - name: "Pigeon"
          ascii_art: "(o.o)"
          hug_message: "{username} feeds the Pigeon. It carries secrets on its wings."
          hunt_message: "{username} catches the Pigeon. Sometimes information comes with feathers."
        - name: "Alley Cat"
          ascii_art: "=^..^=~"
          hug_message: "{username} and the Alley Cat share a smoke. They've both seen better days."
          hunt_message: "{username} wins over the Alley Cat. In this city, even the strays need protection."
        - name: "Guard Dog"
          ascii_art: "[O_O]"
          hug_message: "{username} approaches cautiously. Guard dogs don't trust strangers."
          hunt_message: "{username} handles the Guard Dog. Every fortress has its loyal defenders."
        - name: "Rooftop Crow"
          ascii_art: "<{o}>"
          hug_message: "{username} watches the Crow. It sees everything from above."
          hunt_message: "{username} captures the Crow. Witnesses can be persuaded to talk."
        - name: "Junkyard Dog"
          ascii_art: "[o_O']"
          hug_message: "{username} makes friends with the Junkyard Dog. It's learned to survive."
          hunt_message: "{username} deals with the Junkyard Dog. Some animals are as tough as the streets."
        - name: "Sewer Rat"
          ascii_art: "<:3 )~~~"
          hug_message: "{username} finds common ground with the Sewer Rat. They both know the underbelly of the city."
          hunt_message: "{username} corners the Sewer Rat. Sometimes you have to get your hands dirty."
        - name: "Newsboy's Dog"
          ascii_art: "[o_o]~"
          hug_message: "{username} gives the Newsboy's Dog a treat. It helps deliver the truth."
          hunt_message: "{username} befriends the Newsboy's Dog. The best informants have four legs."